---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[fender-elasticsearch]
      - recipe[fender-elasticsearch::nginx]
    attributes:
      ec2:
        instance_id: 'f1e2d3c'
